dist: xenial
language: node_js
node_js:
  - 16.14.0

install:
  - npm install

branches:
  only:
    - main

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0

deploy:
  provider: heroku
  api_key: f00dd0ed-c091-454b-a65d-345930164663
  app:
    main: careus-frontend-web
